services:
  netmon:
    build: .
    container_name: netmon
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - /proc/1/net:/host/net:ro
      - /root/.ssh/id_firewalla:/root/.ssh/id_firewalla:ro
      - netmon_data:/data
    env_file: .env
    networks:
      br0:
        ipv4_address: ${CONTAINER_IP}
        mac_address: "02:42:0a:00:09:2f"

networks:
  br0:
    external: true

volumes:
  netmon_data:
